apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-board-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end-board-api
  template:
    metadata:
      labels:
        app: back-end-board-api
    spec:
      containers:
        - name: back-end-board-api
          image: blueskii68/back-end-board-api:TAG

---

apiVersion: v1
kind: Service
metadata:
  name: back-end-board-api
spec:
  #type: NodePort #ingress 사용시 주석
  ports:
    - protocol: TCP
      #nodePort: 30082 #ingress 사용시 주석
      port: 30082
      targetPort: 80 
  selector:
    app: back-end-board-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-end-board-api
  annotations:
    # 정규식 경로를 사용
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: blueskii.iptime.org
    - http:
        paths:
          - path: /board(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: back-end-board-api
                port:
                  number: 30082
